content:
  - name: about
    label: data
    type: file
    path: src/data.md
    fields:
      - name: contact
        type: object
        label: contact info
        fields:
          - name: waNum
            type: string
            label: رقم الواتساب
          - name: phoneNum
            type: string
            label: رقم الهاتف
          - name: formLink
            type: string
            hidden: true
            default: wa.me/+
          - name: location
            type: string
            label: الموقع
      - name: socials
        label: socials
        type: object
        list: true
        fields:
          - name: name
            type: string
            options:
              values: [facebook, instagram, whatsapp, x]
          - name: link
            label: الرابط
            type: string
      - name: testmoniels
        label: الأراء
        type: object
        list: true
        fields:
          - name: name
            type: string
            label: الأسم
          - name: text
            type: string
            label: الرأي
          - name: avatar
            type: string
            hidden: true
      - name: services
        label: services
        type: object
        list: true
        fields:
          - name: title
            type: string
            label: الخدمة
          - name: desc
            type: string
            label: الوصف
